spring:
  zipkin:
    baseUrl:  http://localhost:9411

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: TRACE
      org.springframework.web: TRACE
      com.thoughtmechanix: TRACE

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

debug:
  request: true
zuul:
  prefix:  /api
  routes:
    organizationservice: /organization/**

zuul.sensitiveHeaders: Cookie,Set-Cookie
